# Generated by Django 4.2.3 on 2023-11-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='detail',
        ),
        migrations.AddField(
            model_name='feature',
            name='Value',
            field=models.FloatField(default=0),
        ),
    ]
